# [PROJECTS]
#   - k8s-artifacts-prod
#   - k8s-artifacts-prod-bak
#   - k8s-cip-test-prod
#   - k8s-staging-cip-test
#   - k8s-gcr-backup-test-prod
#   - k8s-gcr-backup-test-prod-bak
#   - k8s-gcr-audit-test-prod
#   - k8s-release-test-prod
#
# [REGIONS]
#
#   - us
#   - eu
#   - asia

google_project:
  - name: "[PROJECT]"
google_project_service:
  - service: containerregistry.googleapis.com
    project: "[PROJECT]"
  - service: containeranalysis.googleapis.com
    project: "[PROJECT]"
  - service: storage-component.googleapis.com
    project: "[PROJECT]"
google_container_registry:
  project: "[REGION]_[PROJECT]"
google_storage_bucket:
  - name: "[PROJECT]"
    bucket_policy_only: true
    location: us
    retention_policy:
      retention_period: 315360000 # 10 years
  - name: "[REGION].artifacts.k8s-staging-[PROJECT].appspot.com"
    bucket_policy_only: true
  # START: Additional components for project: "k8s-artifacts-prod"
  - name: k8s-artifacts-prod
    website:
      main_page_suffix: index.html
    project: k8s-artifacts-prod
  - name: k8s-artifacts-cni
    location: us
    bucket_policy_only: true
    retention_policy:
      retention_period: 315360000 # 10 years
    project: k8s-artifacts-prod
  # END
google_project_iam_binding:
  - role: roles/viewer
    members:
      - group:k8s-infra-artifact-admins@kubernetes.io
    project: "[PROJECT]"
  # START: Additional components for project: "k8s-artifacts-prod"
  - role: roles/run.admin
    members:
      - group:k8s-infra-artifact-admins@kubernetes.io
    project: k8s-artifacts-prod
  - role: roles/serviceusage.serviceUsageConsumer
    members:
      - group:k8s-infra-artifact-admins@kubernetes.io
    project: k8s-artifacts-prod
  - role: roles/logging.logWriter
    members:
      - serviceAccount:k8s-infra-gcr-auditor@k8s-artifacts-prod.iam.gserviceaccount.com
    project: k8s-artifacts-prod
  - role: roles/errorreporting.writer
    members:
      - serviceAccount:k8s-infra-gcr-auditor@k8s-artifacts-prod.iam.gserviceaccount.com
    project: k8s-artifacts-prod
  # END
  # START: Additional components for project: "k8s-cip-test-prod"
  - role: roles/viewer
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    project: k8s-cip-test-prod
  # END
  # START: Additional components for project: "k8s-staging-cip-test"
  - role: roles/viewer
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    project: k8s-staging-cip-test
  # END
  # START: Additional components for project: "k8s-gcr-backup-test-prod"
  - role: roles/viewer
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    project: k8s-gcr-backup-test-prod
  # END
  # START: Additional components for project: "k8s-gcr-backup-test-prod-bak"
  - role: roles/viewer
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    project: k8s-gcr-backup-test-prod-bak
  # END
  # START: Additional components for project: "k8s-gcr-audit-test-prod"
  - role: roles/viewer
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    project: k8s-gcr-audit-test-prod
  - role: roles/errorreporting.admin
    members:
      - serviceAccount:k8s-infra-gcr-promoter@k8s-gcr-audit-test-prod.iam.gserviceaccount.com
    project: k8s-gcr-audit-test-prod
  - role: roles/logging.admin
    members:
      - serviceAccount:k8s-infra-gcr-promoter@k8s-gcr-audit-test-prod.iam.gserviceaccount.com
    project: k8s-gcr-audit-test-prod
  - role: roles/pubsub.admin
    members:
      - serviceAccount:k8s-infra-gcr-promoter@k8s-gcr-audit-test-prod.iam.gserviceaccount.com
    project: k8s-gcr-audit-test-prod
  - role: roles/resourcemanager.projectIamAdmin
    members:
      - serviceAccount:k8s-infra-gcr-promoter@k8s-gcr-audit-test-prod.iam.gserviceaccount.com
    project: k8s-gcr-audit-test-prod
  - role: roles/run.admin
    members:
      - serviceAccount:k8s-infra-gcr-promoter@k8s-gcr-audit-test-prod.iam.gserviceaccount.com
    project: k8s-gcr-audit-test-prod
  - role: roles/serverless.serviceAgent
    members:
      - serviceAccount:k8s-infra-gcr-promoter@k8s-gcr-audit-test-prod.iam.gserviceaccount.com
    project: k8s-gcr-audit-test-prod
  - role: roles/storage.admin
    members:
      - serviceAccount:k8s-infra-gcr-promoter@k8s-gcr-audit-test-prod.iam.gserviceaccount.com
    project: k8s-gcr-audit-test-prod
  # END
  # START: Additional components for project: "k8s-release-test-prod"
  - role: roles/viewer
    members:
      - group:k8s-infra-staging-kubernetes@kubernetes.io
      - group:k8s-infra-staging-release-test@kubernetes.io
    project: k8s-release-test-prod
  # END
# START: Additional components for project: "k8s-artifacts-prod"
google_service_account:
  - account_id: k8s-infra-gcr-auditor
    display_name: k8s-infra container image auditor
    project: k8s-artifacts-prod
  - account_id: k8s-infra-gcr-auditor-invoker
    display_name: k8s-infra container image auditor invoker
    project: k8s-artifacts-prod
google_service_account_iam_binding:
  - service_account_id: k8s-infra-gcr-auditor@k8s-artifacts-prod.iam.gserviceaccount.com
    role: roles/iam.serviceAccountUser
    members:
      - group:k8s-infra-artifact-admins@kubernetes.io
google_cloud_run_service_iam_binding:
  service_name: cip-auditor
  role: roles/run.invoker
  members:
    - serviceAccount:k8s-infra-gcr-auditor-invoker@k8s-artifacts-prod.iam.gserviceaccount.com
  location: us-central1
  project: k8s-artifacts-prod
google_storage_bucket_object:
# We'll be copying all static files from "static/prod-storage"
  - name: "[NAME]"
    source: "[MODULE_PATH]/static/prod-storage/[FILE]"
    bucket: gs://k8s-artifacts-prod
# END
google_storage_bucket_iam_binding:
  # gs://[PROJECT]
  - role: roles/storage.objectViewer
    members:
      - allUsers
    bucket: gs://[PROJECT]
  - role: roles/storage.objectAdmin
    members:
      - group:k8s-infra-artifact-admins@kubernetes.io
    bucket: gs://[PROJECT]
  - role: roles/storage.legacyBucketOwner
    members:
      - group:k8s-infra-artifact-admins@kubernetes.io
    bucket: gs://[PROJECT]
  # gs://[REGION].artifacts.k8s-staging-[PROJECT].appspot.com
  - role: roles/storage.objectViewer
    members:
      - allUsers
    bucket: gs://[REGION].artifacts.k8s-staging-[PROJECT].appspot.com
  - role: roles/storage.objectAdmin
    members:
      - group:k8s-infra-artifact-admins@kubernetes.io
      - serviceAccount:k8s-infra-gcr-promoter@[PROJECT].iam.gserviceaccount.com
    bucket: gs://[REGION].artifacts.k8s-staging-[PROJECT].appspot.com
  - role: roles/storage.legacyBucketOwner
    members:
      - group:k8s-infra-artifact-admins@kubernetes.io
      - serviceAccount:k8s-infra-gcr-promoter@[PROJECT].iam.gserviceaccount.com
    bucket: gs://[REGION].artifacts.k8s-staging-[PROJECT].appspot.com
  # gs://k8s-artifacts-cni
  # START: Additional components for project: "k8s-artifacts-prod"
  - role: roles/storage.objectViewer
    members:
      - allUsers
    bucket: gs://k8s-artifacts-cni
  - role: roles/storage.objectAdmin
    members:
      - group:k8s-infra-artifact-admins@kubernetes.io
      - group:k8s-infra-push-cni@kubernetes.io
    bucket: gs://k8s-artifacts-cni
  - role: roles/storage.legacyBucketOwner
    members:
      - group:k8s-infra-artifact-admins@kubernetes.io
    bucket: gs://k8s-artifacts-cni
  - role: roles/storage.legacyBucketReader
    members:
      - group:k8s-infra-push-cni@kubernetes.io
    bucket: gs://k8s-artifacts-cni
  # END
  # START: Additional components for project: "k8s-cip-test-prod"
  - role: roles/storage.objectAdmin
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    bucket: gs://[REGION].artifacts.k8s-cip-test-prod.appspot.com
  - role: roles/storage.legacyBucketOwner
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    bucket: gs://[REGION].artifacts.k8s-cip-test-prod.appspot.com
  # END
  # START: Additional components for project: "k8s-staging-cip-test"
  - role: roles/storage.objectAdmin
    members:
      - serviceAccount:k8s-infra-gcr-promoter@k8s-cip-test-prod.iam.gserviceaccount.com
    bucket: gs://artifacts.k8s-staging-cip-test.appspot.com
  - role: roles/storage.legacyBucketOwner
    members:
      - serviceAccount:k8s-infra-gcr-promoter@k8s-cip-test-prod.iam.gserviceaccount.com
    bucket: gs://artifacts.k8s-staging-cip-test.appspot.com
  - role: roles/storage.objectAdmin
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    bucket: gs://[REGION].artifacts.k8s-staging-cip-test.appspot.com
  - role: roles/storage.legacyBucketOwner
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    bucket: gs://[REGION].artifacts.k8s-staging-cip-test.appspot.com
  # END
  # START: Additional components for project: "k8s-gcr-backup-test-prod"
  - role: roles/storage.objectAdmin
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    bucket: gs://[REGION].artifacts.k8s-gcr-backup-test-prod.appspot.com
  - role: roles/storage.legacyBucketOwner
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    bucket: gs://[REGION].artifacts.k8s-gcr-backup-test-prod.appspot.com
  # END
  # START: Additional components for project: "k8s-gcr-backup-test-prod-bak"
  - role: roles/storage.objectAdmin
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    bucket: gs://[REGION].artifacts.k8s-gcr-backup-test-prod-bak.appspot.com
  - role: roles/storage.legacyBucketOwner
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    bucket: gs://[REGION].artifacts.k8s-gcr-backup-test-prod-bak.appspot.com
  # END
  # START: Additional components for project: "k8s-gcr-audit-test-prod"
  - role: roles/storage.objectAdmin
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    bucket: gs://[REGION].artifacts.k8s-gcr-audit-test-prod.appspot.com
  - role: roles/storage.legacyBucketOwner
    members:
      - group:k8s-infra-staging-cip-test@kubernetes.io
    bucket: gs://[REGION].artifacts.k8s-gcr-audit-test-prod.appspot.com
  # END
  # START: Additional components for project: "k8s-release-test-prod"
  - role: roles/storage.objectAdmin
    members:
      - serviceAccount:615281671549@cloudbuild.gserviceaccount.com
    bucket: gs://k8s-release-test-prod
  - role: roles/storage.legacyBucketOwner
    members:
      - serviceAccount:615281671549@cloudbuild.gserviceaccount.com
    bucket: gs://k8s-release-test-prod
  - role: roles/storage.objectAdmin
    members:
      - group:k8s-infra-staging-kubernetes@kubernetes.io
      - group:k8s-infra-staging-release-test@kubernetes.io
    bucket: gs://[REGION].artifacts.k8s-release-test-prod.appspot.com
  - role: roles/storage.legacyBucketOwner
    members:
      - group:k8s-infra-staging-kubernetes@kubernetes.io
      - group:k8s-infra-staging-release-test@kubernetes.io
    bucket: gs://[REGION].artifacts.k8s-release-test-prod.appspot.com
  # END